### ISSUE TITLE
Unable to run test case#1 with JDK11.0.1 

### ISSUE THREAD

**Issue by Nandansv** [corda/corda-training-template#26]
Hi Team,
I am now trying to run first IOUState Test from IntelliJ IDEA.
I've configured jdk11.0.1 for this in project structure.
When i am trying to execute first assignment . Its not able to identify the JDK version on my system.
Could you please look at it.
> Could not determine Java version using executable C:\Program Files\Java\jdk-11.0.1\bin\java.exe.

The problem is... Its unable to implement the interface "ContractState" .
So, when i am trying to run the test again after declaring amount variable "val amount : Amount<currency>" .. 
Its unable to identify the Amount and currency keywords and throwing below error,

> e: E:\BlockChain\Corda\corda-training-template\kotlin-source\src\main\kotlin\net\corda\training\state\IOUState.kt: (12, 34): Unresolved reference: Amount
> e: E:\BlockChain\Corda\corda-training-template\kotlin-source\src\main\kotlin\net\corda\training\state\IOUState.kt: (12, 41): Unresolved reference: currency
> :kotlin-source:compileKotlin FAILED
> 
> FAILURE: Build failed with an exception.

**PS:Meanwhile , I am trying to configure JDK8 and will provide my observations.**

**Comment by amoothart** [comment]
Hi @Nandansv, yes at this point Corda only using Java 8. We're currently building in support for future versions of Java. Once that is available we'll upgrade the training applications.
