### ISSUE TITLE
IOUSettleTests.kt

### ISSUE THREAD

**Issue by RemoFiorentino** [corda/corda-training-template#34]
It looks like there is a bug with the solution as I am trying to run the first test of IOUSettleTests.kt it gives me error. 

I got it working by changing the string message in IOUSettleTests.kt

in line 61 `this.failsWith("Contact Verification Failed");`

by `this.failsWith("Contract verification failed")`

Noticed it was different in the Corda-training-solution repo.

`java.lang.AssertionError: Expected exception containing 'Contact Verification Failed' but raised exception was 'net.corda.core.contracts.TransactionVerificationException$ContractRejection: Contract verification failed: Required net.corda.training.contract.IOUContract.Commands command, contract: net.corda.training.contract.IOUContract, transaction: 44A4FD321412407AB9F7C2F6B1AAD494284F0CF140A7FEC8F58AF7FB09FAF65D'`

**Comment by rogersanick** [comment]
Thanks @RemoFiorentino! This is really helpful. I'll add a fix asap.
